export enum CombatEvents {
    CombatClock = 'combatClock',
    StartCombat = 'startCombat',
    CombatResult = 'combatResult',
    CombatAborted = 'combatAborted',
    CombatMove = 'combatMove',
    AttackResult = 'attackResult',
    CombatTurnExpired = 'combatTurnExpired',
    YourAttack = 'yourAttack',
    YourDefense = 'yourDefense',
    RunFailed = 'runFailed',
    NextCombatTurn = 'nextCombatTurn',
    CombatEnded = 'combatEnded',
    ContinueTurn = 'continueTurn',
}
