export enum GameLogicEvents {
    Clock = 'clock',

    StartGame = 'startGame',
    InitialiseGame = 'initialiseGame',
    PauseGame = 'pauseGame',
    StopGame = 'stopGame',
    PassTurn = 'passTurn',
    ContinueTurn = 'continueTurn',
    TurnStarted = 'turnStarted',
    TurnEnded = 'turnEnded',
    MovePlayer = 'movePlayer',
    UpdateMap = 'updateMap',
    GameOver = 'gameOver',
    GameOverStats = 'gameOverStats',
    GameAborted = 'gameAborted',
    UpdatePlayerPos = 'updatePlayerPos',
    GameLog = 'gameLog',
    GetInitialLogs = 'getInitialLogs',
    UpdatePlayerSpeed = 'updatePlayerSpeed',
    ToggleDoor = 'toggleDoor',
    PlayersUpdate = 'playersUpdate',
    AvailableTiles = 'availableTiles',
    ToggleDebugMode = 'toggleDebugMode',
    VirtualPlayerTurn = 'virtualPlayerTurn',
    UpdateFlag = 'updateFlag',
    TeleportPlayer = 'teleportPlayer',

    UpdateAttribute = 'updateAttribute',
    UpdatePlayerInventory = 'updatePlayerInventory',
    NewInventory = 'newInventory',
    RejectedItem = 'rejectedItem',
}
